version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
cache: C:\Users\appveyor\.dnx
build_script:
- cmd: >-
    cd ./Ybm.Infrastructure.Core

    dotnet restore
    
    dotnet build -c release

    dotnet pack -c release

    cd ../..

artifacts:
- path: ./Ybm.Infrastructure.Core/bin/release/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 5rLhFBIO+e9MoMP6ElXE/oJkUihjIh/86FA4UOuLJWdnezT04BzLmnGyYxrgKN75
  skip_symbols: true
notifications:
- provider: Email
  to:
  - unos.bm65@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true